### ISSUE TITLE
样式丢失：非根css选择器的情况下会丢失

### ISSUE THREAD

**Issue by czzonet** [xyl66/vuePlugs_printjs#36]
问题
===

一次写scss多层嵌套后发现样式丢失，经过观察，发现dom样式不同。有多层选择器时打印样式丢失，唯一选择器时正常。

情况描述
---
打印节点
```html
<div class="father">
<div class="print ref="printnode">Here is something to print!</div>
</div>
```
scss样式
样式丢失的情况：
```scss
.father{
.print{
color:red;
}
}
```
样式正常的情况：
```scss
.father{
}
.print{
color:red;
}
```
总结
---
目前可以在使用时写根选择器样式解决，希望后续能修复此问题。
