### ISSUE TITLE
能支持设置打印预览默认A5吗？

### ISSUE THREAD

**Issue by SamHz** [xyl66/vuePlugs_printjs#4]
能支持设置打印预览默认A5吗？

**Comment by terasa-J** [comment]
同问

**Comment by nsznsznjsz** [comment]
试试 css
```css
@page {
  size: A5;
}
```
